TARGET_URL = 'https://spinningline.ru/'
TARGET_PATH = 'yummy-m-46428.html'
NAVIGATION_NAME = 'page='
USER_AGENT = 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.1; Trident/4.0)'
MARKUP_ANALYZER = 'lxml'